 CREATE TABLE "SYSTEM"."USER_INFO" 
   (   "USER_ID" NUMBER primary key, 
   "USERNAME" VARCHAR2(32 BYTE) NOT NULL, 
   "PASSWORD" VARCHAR2(100 BYTE) NOT NULL, 
   "MAIL_ADDRESS" VARCHAR2(256 BYTE) NOT NULL, 
   "TEL" VARCHAR2(32 BYTE) NOT NULL, 
   "ZONECODE" NUMBER, 
   "ADDRESS" VARCHAR2(256 BYTE), 
   "ADDRESS2" VARCHAR2(256 BYTE)
);
 CREATE TABLE "SYSTEM"."USER_ROLE" 
   (   "ROLE_ID" NUMBER, 
   "USER_ID" NUMBER NOT NULL, 
   "ROLE" VARCHAR2(32 BYTE) NOT NULL, 
    PRIMARY KEY ("ROLE_ID")
     );
     
CREATE SEQUENCE  user_info_seq;
CREATE SEQUENCE  user_role_seq;
     
CREATE SEQUENCE USER_INFO;
CREATE SEQUENCE USER_ROLE;

SELECT
    *
FROM "SYSTEM"."USER_INFO" ;


DROP SEQUENCE USER_INFO;
DROP  SEQUENCE USER_ROLE;